// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether workflow subscribers also receive normal node thread events.
 */
export type NodeThreadSubscription = "include" | "referencesOnly";
