// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowDefinitionStability } from "./WorkflowDefinitionStability";

/**
 * Discovery metadata for one exact registered workflow version.
 */
export type WorkflowDefinitionSummary = { name: string, version: string, description: string, isDefault: boolean, stability: WorkflowDefinitionStability, stateSchemaVersion: number, argvHelp: string, argumentSchema: unknown, outputSchema: unknown, requiredCapabilities: Array<string>, };
