// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowNodeStatus } from "./WorkflowNodeStatus";

export type WorkflowNodeUpdatedNotification = { runId: string, sequence: bigint, createdAtMs: bigint, nodeId: string, threadId: string | null, status: WorkflowNodeStatus | null, metadata: unknown, };
