// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowArtifactSummary } from "./WorkflowArtifactSummary";
import type { WorkflowNodeSummary } from "./WorkflowNodeSummary";
import type { WorkflowRunStatus } from "./WorkflowRunStatus";

/**
 * Durable run snapshot returned by workflow requests.
 */
export type WorkflowRun = { runId: string, workflowName: string, workflowVersion: string, status: WorkflowRunStatus, arguments: unknown, nonInteractive: boolean, detached: boolean, concurrency: number | null, output: unknown, errorCode: string | null, wake: unknown, nextSequence: bigint, nodes: Array<WorkflowNodeSummary>, artifacts: Array<WorkflowArtifactSummary>, createdAtMs: bigint, updatedAtMs: bigint, };
