// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Durable workflow node lifecycle state.
 */
export type WorkflowNodeStatus = "pending" | "ready" | "running" | "waiting" | "succeeded" | "failed" | "cancelled" | "blocked";
