// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Durable artifact manifest safe to expose through workflow run snapshots.
 */
export type WorkflowArtifactSummary = { artifactId: string, relativePath: string, classification: string, mediaType: string, sizeBytes: bigint, sha256: string, createdAtMs: bigint, };
