// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowNodeStatus } from "./WorkflowNodeStatus";

/**
 * One node included in a workflow run snapshot.
 */
export type WorkflowNodeSummary = { nodeId: string, nodeKey: string, threadId: string | null, status: WorkflowNodeStatus, retryAtMs: bigint | null, createdAtMs: bigint, updatedAtMs: bigint, };
