// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Redacted, monotonically sequenced workflow orchestration event.
 */
export type WorkflowEvent = { runId: string, sequence: bigint, kind: string, entityId: string | null, metadata: unknown, createdAtMs: bigint, };
