// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stability classification published by a registered workflow.
 */
export type WorkflowDefinitionStability = "experimental" | "stable";
