// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowRunStatus } from "./WorkflowRunStatus";

export type WorkflowRunUpdatedNotification = { runId: string, sequence: bigint, createdAtMs: bigint, status: WorkflowRunStatus, metadata: unknown, };
