// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Durable workflow run lifecycle state.
 */
export type WorkflowRunStatus = "pending" | "running" | "waiting" | "cancelling" | "succeeded" | "failed" | "cancelled" | "needsOperator";
