// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Arguments supplied to one registered workflow definition.
 */
export type WorkflowArgumentsInput = { "kind": "argv", argv: Array<string>, } | { "kind": "json", value: unknown, };
