//! Version-pinned `fornax-cli` adapters.

mod bridge_config;
mod bridge_daemon;
mod bridge_http;
mod bridge_protocol;
mod cli_config;
mod cli_version;
mod delivery;
mod durable_trace_write;
mod error;
mod evaluation;
mod prompt;
pub(crate) mod redaction;
mod skill;
mod span_semantics;
mod trace_read;
mod trace_write;
mod types;
mod workflow_client;

pub use bridge_config::FornaxBridgeConfig;
pub use bridge_config::FornaxBridgeEnvironment;
pub use bridge_config::FornaxBridgeError;
pub use bridge_daemon::DiscoveryStatus;
pub use bridge_daemon::FornaxBridgeDiscovery;
pub use bridge_daemon::ensure_bridge;
pub use bridge_http::FornaxBridgeHttpClient;
pub use bridge_protocol::BridgeErrorEnvelope;
pub use bridge_protocol::BridgeHealth;
pub use bridge_protocol::FORNAX_BRIDGE_PROTOCOL;
pub use bridge_protocol::FORNAX_BRIDGE_VERSION;
pub use bridge_protocol::FORNAX_SDK_VERSION;
pub use bridge_protocol::FinishSpanRequest;
pub use bridge_protocol::FinishedSpan;
pub use bridge_protocol::HealthState;
pub use bridge_protocol::OperationState;
pub use bridge_protocol::OperationStatus;
pub use bridge_protocol::RecordKind;
pub use bridge_protocol::RecordSpanRequest;
pub use bridge_protocol::RecordedSpan;
pub use bridge_protocol::RetryDisposition;
pub use bridge_protocol::SpanParent;
pub use bridge_protocol::SpanRecord;
pub use bridge_protocol::SpanState;
pub use bridge_protocol::SpanStatus;
pub use bridge_protocol::SpanType;
pub use bridge_protocol::StartSpanRequest;
pub use bridge_protocol::StartedSpan;
pub use cli_config::FornaxCli;
pub use cli_config::FornaxCliConfig;
pub use cli_config::FornaxCliEnvironment;
pub use cli_version::FornaxCliCapabilities;
pub use cli_version::FornaxCliVersion;
pub use delivery::FornaxDeliveryError;
pub use delivery::FornaxDeliveryReport;
pub use delivery::FornaxDeliveryReporter;
pub use delivery::FornaxDeliveryState;
pub use durable_trace_write::DurableFornaxTraceError;
pub use durable_trace_write::DurableFornaxTraceWriter;
pub use durable_trace_write::FornaxSpanCorrelation;
pub use error::FornaxCliError;
pub use evaluation::ExperimentEvaluatorOnlyRequest;
pub use evaluation::FornaxPageRequest;
pub use prompt::PromptDraft;
pub use prompt::PromptDraftValidationError;
pub use prompt::PromptRenderError;
pub use prompt::render_normal_prompt;
pub use span_semantics::FornaxSpanInput;
pub use span_semantics::FornaxSpanOutput;
pub use span_semantics::FornaxSpanSemanticError;
pub use span_semantics::TraceContent;
pub use span_semantics::TraceMessage;
pub use span_semantics::TracePromptArgument;
pub use span_semantics::TracePromptArgumentSource;
pub use trace_write::FornaxTraceWriter;
pub use trace_write::digest_record;
pub use trace_write::safe_tags;
pub use types::FornaxPrompt;
pub use types::FornaxPromptMessage;
pub use types::FornaxSkill;
pub use types::FornaxSpan;
pub use types::FornaxTrajectory;
pub use types::PromptLookup;
pub use types::SkillLookup;
pub use types::SpanListRequest;
pub use types::SpanPage;
pub use types::TimeWindow;
pub use types::TraceGetRequest;
pub use types::TraceListRequest;
pub use types::TraceLookup;
pub use types::TracePage;
pub use types::TrajectoryLookup;
pub use workflow_client::FornaxCapabilityError;
pub use workflow_client::FornaxWorkflowClient;
