//! Experimental typed definitions and feasibility work for persisted Codex workflows.
//!
//! Workflows are replayable reducers over versioned checkpoints. Definitions
//! are registered statically; runtime effects are exposed only through typed,
//! journal-backed capabilities.

pub mod api;
#[doc(hidden)]
pub mod feasibility;
pub mod registry;
pub mod runtime;

pub use api::ArgumentError;
pub use api::ArtifactClassification;
pub use api::ArtifactId;
pub use api::ArtifactMetadata;
pub use api::EffectKey;
pub use api::IdentifierError;
pub use api::InteractionId;
pub use api::NodeApprovals;
pub use api::NodeAttemptId;
pub use api::NodeCollaborationMode;
pub use api::NodeId;
pub use api::NodeInput;
pub use api::NodeKey;
pub use api::NodeModel;
pub use api::NodeReasoningEffort;
pub use api::NodeSandbox;
pub use api::NodeSpec;
pub use api::NodeSpecBuilder;
pub use api::NodeSpecError;
pub use api::NodeTurnResult;
pub use api::NodeTurnStatus;
pub use api::NodeWorkingDirectory;
pub use api::SkillAuthoritySelector;
pub use api::SkillInitialInvocation;
pub use api::SkillPackageSelector;
pub use api::SkillPolicy;
pub use api::SkillSelector;
pub use api::WakeCondition;
pub use api::Workflow;
pub use api::WorkflowArguments;
pub use api::WorkflowCancellation;
pub use api::WorkflowContext;
pub use api::WorkflowError;
pub use api::WorkflowMetadata;
pub use api::WorkflowName;
pub use api::WorkflowNodeBinding;
pub use api::WorkflowNodeLaunch;
pub use api::WorkflowOutput;
pub use api::WorkflowRunId;
pub use api::WorkflowSequence;
pub use api::WorkflowStability;
pub use api::WorkflowState;
pub use api::WorkflowTransition;
pub use api::WorkflowVersion;
pub use registry::RegistryError;
pub use registry::WorkflowCheckpoint;
pub use registry::WorkflowDefinition;
pub use registry::WorkflowDefinitionMetadata;
pub use registry::WorkflowRegistry;
pub use registry::WorkflowRegistryBuilder;
pub use runtime::AwaitTurnRequest;
pub use runtime::ConfirmedHistoryDeletion;
pub use runtime::MaterializeNodeRequest;
pub use runtime::MaterializedNode;
pub use runtime::NodeHostBindError;
pub use runtime::NodeHostError;
pub use runtime::NodeHostFuture;
pub use runtime::NodeRuntimeStatus;
pub use runtime::PreparedTurnDisposition;
pub use runtime::PreparedTurnRequest;
pub use runtime::RuntimeShutdown;
pub use runtime::SteerTurnRequest;
pub use runtime::SubmittedTurn;
pub use runtime::WorkflowArtifactStore;
pub use runtime::WorkflowArtifactStoreError;
pub use runtime::WorkflowArtifactWrite;
pub use runtime::WorkflowNodeHost;
pub use runtime::WorkflowNodeHostSlot;
